version: "3"
services:
  app:
    container_name: admin_pannel_prod
    image: admin_pannel_prod
    restart: always
    build: .
    working_dir: /usr/src/app
    network_mode: host
    volumes:
      - "./:/usr/src/app"
    environment:
      - NODE_ENV=production
    command: >
      bash -c "npm run build && npm start"
   
 